# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

# Get the environment variables shared across all my *nix machines
if [ -f ~/.bash_profile_shared ]; then
  source ~/.bash_profile_shared
fi

# /usr/local stuff Requested by homebrew
export PATH="$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:$PATH"

# Python stuff
export PYTHONPATH="$PYTHONPATH:$HOME/.local/site-packages"

# Command prompt format string
export PS1='\[\033[32m\]imac:\[\033[36;1m\]\W\[\033[m\]\$ '

# iTerm2 stuff
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"
