# .bashrc

# Get the aliases and functions shared across all my *nix machines
if [ -f ~/.bashrc_shared ]; then
  source ~/.bashrc_shared
fi

alias ls='ls -G'
alias l='ls'
alias ll='ls -la'
alias l.='ls -Gd .*'
alias k3='source activate kaggle3'
alias jnremote='echo "Copy the following address into your browser:"; echo "http://localhost:8888"; ssh -N -L localhost:8888:localhost:8889 lindsb@rrlogin.seas.upenn.edu'

# small_funcs contains small functions
source ~/.local/bin/small_funcs.sh

# acd_func adds functionality to the cd command
source ~/.local/bin/cd_func.sh

# Source bash_completion if available
if [ -f /usr/local/etc/bash_completion ]; then
  source /usr/local/etc/bash_completion
fi

if [ -f /usr/local/etc/bash_completion.d/passtail ]; then
  source /usr/local/etc/bash_completion.d/passtail
fi
