if [ -z $PS1 ]; then
  source $HOME/.bashrc
else
#   read -p "Use zsh? (y/n) " -n 1 -r
#   if [[ $REPLY =~ ^[Yy]$ ]]; then
#     echo
#     echo "Good choice! zsh it is."
#     export SHELL=/bin/zsh
#     exec /bin/zsh -l
#   else
    echo
    echo "Bummer. Here's your bash shell."
    source $HOME/.bashrc
    export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[36;1m\]\W\[\033[m\]\$ "
#   fi
fi
