# .bashrc

#------------------------------------------------------------------
# Source global definitions
#------------------------------------------------------------------
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

#------------------------------------------------------------------
# Aliases and functions specific to rrlogin
#------------------------------------------------------------------

module load intel-11.1
module load openmpi-1.4.3-intel

#------------------------------------------------------------------
# Source aliases and functions I share with all my *nix machines
#------------------------------------------------------------------
if [ -f ~/.bashrc_shared ]; then
  . ~/.bashrc_shared
fi
