# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# Get environment variables that are common to all my *nix machines
if [ -f ~/.bash_profile_shared ]; then
  . ~/.bash_profile_shared
fi

# Path environment variables
export PATH="$HOME/bin:$HOME/usr/miniconda/bin:$HOME/usr/paraview/bin:$PATH"
export PATH="$PATH:$HOME/usr/site-packages/data_utils"
export PYTHONPATH="$PYTHONPATH:/home/lindsb/usr/site-packages"
export PYTHONPATH="$PYTHONPATH:/home/lindsb/studies/film_stamp/code"
export FFTWHOME="$HOME/usr/fftw_mpi"
export FFTW_OPENMP="$HOME/usr/fftw_openmp"

export PATH="$PATH:$HOME/usr/texlive/bin/x86_64-linux"
export INFOPATH="$HOME/usr/texlive/texmf-dist/doc/info:$INFOPATH"
export MANPATH="$HOME/usr/texlive/texmf-dist/doc/man:$MANPATH"

export CPLUS_INCLUDE_PATH="$HOME/usr/boost/include:$CPLUS_INCLUDE_PATH"
export LIBRARY_PATH="$HOME/usr/boost/lib:$LIBRARY_PATH"

export EDITOR="$HOME/bin/vim"

export PATH=$HOME/cctools/bin:$PATH

export NP_PMF_PROJ="$HOME/studies/np-pmf"
export BCP_NP_PHASE_PROJ="$HOME/studies/bcp-np-phase"

# Color and format terminal prompt
# Courtesy of osxdaily.com/2013/02/05/improve-terminal-appearance-mac-os-x/
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[36;1m\]\W\[\033[m\]\$ "

# iterm2 stuff
export iterm2_hostname=rrlogin.seas.upenn.edu
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
