# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

# Get environment variables shared across all my *nix machines
if [ -f ~/.bash_profile_shared ]; then
  source ~/.bash_profile_shared
fi

export HOSTNAME_SHORT="mac"

# Added by Anaconda 2.1.0 installer on 1/14/2015
# export PATH="$HOME/anaconda/bin:$PATH"

# Add path to pvpython executable
# export PATH="$PATH:/Applications/paraview.app/Contents/bin"

# Add path to local functions
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Path to mysql
# export PATH="$PATH:/Applications/MAMP/Library/bin"

# path to paraview packages
# export PYTHONPATH="/Applications/paraview.app/Contents/Python"

export PYTHONPATH="$HOME/.local/site-packages"

# Color and reformat terminal prompt
PS1="\[\033[32m\]macbook:\[\033[36;1m\]\W\[\033[m\]\$ "

# Load RVM into a shell session *as a function*
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# rbenv lines recommended by homebrew
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
