# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

# Get environment variables shared across all my *nix machines
if [ -f ~/.bash_profile_shared ]; then
  source ~/.bash_profile_shared
fi

# Source bash_completion if available
if [ -f /usr/local/etc/bash_completion ]; then
  source /usr/local/etc/bash_completion
fi

# Modify PATH
export PATH="$HOME/local/bin:$PATH"

# Color and reformat terminal prompt
PS1="\[\033[32m\]android:\[\033[36;1m\]\W\[\033[m\]\$ "
