# .bashrc

#------------------------------------------------------------------
# Source global definitions
#------------------------------------------------------------------
if [ -f /etc/bashrc ]; then
  source /etc/bashrc
fi

#------------------------------------------------------------------
# Source aliases and functions shared across all my *nix machines
#------------------------------------------------------------------
if [ -f ~/.bashrc_shared ]; then
  source ~/.bashrc_shared
fi

#------------------------------------------------------------------
# Aliases for commands
#------------------------------------------------------------------

alias l='ls'
alias ll='ls -la'
